spring:
  application.name: demo-service

  data.mongodb:
    host: localhost
    port: 27017
    database: demo
    username: demo_application
    password: demo_password
    auto-index-creation: true

logging:
  level:
    org.springframework.cache: TRACE